name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 3.0.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.2'
      - name: Run Dependencies
        run: make install
      - name: Run Tests
        run: make tests
      - name: Run Rubocop
        run: make lint